<?php namespace ProcessWire;

/** Built-in multilingual ProcessWire community showcase catalogue. */
trait LynxDemoProfiles {

    /** Built-in demo profiles used by Lynx Manager for first-run onboarding. */
    public function demoProfilesExport() {
        $link = function($label, $url, $icon, $sort, $isSocial, $altLang, $altLabel) {
            return array(
                'label' => $label,
                'url' => $url,
                'icon' => $icon,
                'is_social' => $isSocial ? 1 : 0,
                'start_date' => 0,
                'end_date' => 0,
                'sort' => $sort,
                'active' => 1,
                'translations' => array($altLang => array('label' => $altLabel)),
            );
        };
        $project = function(array $p) {
            $lang = $p['alt']['lang'];
            return array(
                'type' => 'project',
                'title' => $p['project_title'],
                'data' => array('items' => array(array(
                    'heading' => $p['project_name'],
                    'body' => $p['project_body'],
                    'image' => $p['project_image'],
                    'link' => $p['project_url'],
                    'linkLabel' => $p['project_label'],
                ))),
                'sort' => 0,
                'active' => 1,
                'translations' => array($lang => array(
                    'title' => $p['alt']['project_title'],
                    'data' => array('items' => array(array(
                        'heading' => $p['project_name'],
                        'body' => $p['alt']['project_body'],
                        'linkLabel' => $p['alt']['project_label'],
                    ))),
                )),
            );
        };
        $quote = function(array $p) {
            $lang = $p['alt']['lang'];
            return array(
                'type' => 'quote',
                'title' => $p['record_title'],
                'data' => array('quotes' => array(array(
                    'text' => $p['record_text'],
                    'author' => $p['record_author'],
                    'role' => $p['record_role'],
                ))),
                'sort' => 1,
                'active' => 1,
                'translations' => array($lang => array(
                    'title' => $p['alt']['record_title'],
                    'data' => array('quotes' => array(array(
                        'text' => $p['alt']['record_text'],
                        'author' => $p['record_author'],
                        'role' => $p['alt']['record_role'],
                    ))),
                )),
            );
        };
        $gallery = function(array $p) {
            $lang = $p['alt']['lang'];
            return array(
                'type' => 'gallery',
                'title' => $p['gallery_title'],
                'data' => array(
                    'columns' => 3,
                    'images' => array(
                        array('src' => $p['avatar'], 'caption' => $p['gallery_captions'][0], 'link' => $p['github_url']),
                        array('src' => $p['project_image'], 'caption' => $p['gallery_captions'][1], 'link' => $p['project_url']),
                        array('src' => 'https://d1juguve2xwkcy.cloudfront.net/tpl/css/images/processwire-pink.svg', 'caption' => $p['gallery_captions'][2], 'link' => $p['author_url']),
                    ),
                ),
                'sort' => 2,
                'active' => 1,
                'translations' => array($lang => array(
                    'title' => $p['alt']['gallery_title'],
                    'data' => array('images' => array(
                        array('caption' => $p['alt']['gallery_captions'][0]),
                        array('caption' => $p['alt']['gallery_captions'][1]),
                        array('caption' => $p['alt']['gallery_captions'][2]),
                    )),
                )),
            );
        };
        $video = function(array $p) {
            $lang = $p['alt']['lang'];
            return array(
                'type' => 'video',
                'title' => $p['video_title'],
                'data' => array('videos' => array(array(
                    'url' => 'https://www.youtube.com/watch?v=Wl4XiYadV_k',
                    'caption' => $p['video_caption'],
                ))),
                'sort' => 3,
                'active' => 1,
                'translations' => array($lang => array(
                    'title' => $p['alt']['video_title'],
                    'data' => array('videos' => array(array('caption' => $p['alt']['video_caption']))),
                )),
            );
        };

        $profiles = array(
            array(
                'slug' => 'ryan-cramer',
                'region' => 'Atlanta, Georgia, USA',
                'lang' => 'en',
                'title' => 'Ryan Cramer',
                'bio' => 'Founder and lead developer of ProcessWire. Ryan has focused on development and support of the ProcessWire core since 2006. Unofficial community showcase based on public sources.',
                'avatar' => 'https://d1juguve2xwkcy.cloudfront.net/assets/files/2572/328272_200x0-is-hidpi.400x0.jpg',
                'github_url' => 'https://github.com/ryancramerdesign',
                'author_url' => 'https://processwire.com/about/team/ryan/',
                'project_url' => 'https://github.com/processwire/processwire',
                'project_name' => 'ProcessWire',
                'project_title' => 'Featured project',
                'project_body' => 'The open-source CMS and CMF whose core Ryan has developed and supported since 2006.',
                'project_label' => 'Open repository',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/processwire/processwire',
                'record_title' => 'Official description',
                'record_text' => 'ProcessWire is a friendly and powerful open source CMS with an API.',
                'record_author' => 'ProcessWire',
                'record_role' => 'Official repository description',
                'gallery_title' => 'Public sources',
                'gallery_captions' => array('GitHub profile', 'ProcessWire repository', 'Official ProcessWire profile'),
                'video_title' => 'ProcessWire history',
                'video_caption' => 'The video from the original 2010 open-source release, published on the official ProcessWire history page.',
                'theme' => 'default', 'font' => 'inter', 'accent' => '#2480e6', 'bg_type' => 'color', 'bg_value' => '#f5f7fa',
                'alt' => array(
                    'lang' => 'es',
                    'bio' => 'Fundador y desarrollador principal de ProcessWire. Ryan se ocupa del desarrollo y soporte del núcleo de ProcessWire desde 2006. Muestra comunitaria no oficial basada en fuentes públicas.',
                    'project_title' => 'Proyecto destacado', 'project_body' => 'El CMS y CMF de código abierto cuyo núcleo Ryan desarrolla y mantiene desde 2006.', 'project_label' => 'Abrir repositorio',
                    'record_title' => 'Descripción oficial', 'record_text' => 'ProcessWire es un CMS de código abierto, potente y accesible, con una API.', 'record_role' => 'Descripción oficial del repositorio',
                    'gallery_title' => 'Fuentes públicas', 'gallery_captions' => array('Perfil de GitHub', 'Repositorio de ProcessWire', 'Perfil oficial de ProcessWire'),
                    'video_title' => 'Historia de ProcessWire', 'video_caption' => 'Vídeo del lanzamiento original como código abierto en 2010, publicado en la página oficial de historia de ProcessWire.',
                    'profile_label' => 'Perfil oficial', 'github_label' => 'GitHub', 'project_link_label' => 'ProcessWire',
                ),
            ),
            array(
                'slug' => 'maxim-semenov',
                'region' => 'Media, Pennsylvania, USA',
                'lang' => 'en',
                'title' => 'Maxim Semenov',
                'bio' => 'Full-stack e-commerce developer and ProcessWire module author. His public author page lists Lynx among a broad collection of development, media, SEO and operations modules. Unofficial community showcase based on public sources.',
                'avatar' => 'https://avatars.githubusercontent.com/u/36412557?v=4',
                'github_url' => 'https://github.com/mxmsmnv',
                'author_url' => 'https://processwire.com/modules/author/maxim-semenov/',
                'project_url' => 'https://github.com/mxmsmnv/Ichiban',
                'project_name' => 'Ichiban',
                'project_title' => 'Featured project',
                'project_body' => 'A comprehensive SEO module for ProcessWire CMS.',
                'project_label' => 'Open repository',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/mxmsmnv/Ichiban',
                'record_title' => 'Public author record',
                'record_text' => 'Full-Stack E-commerce Developer',
                'record_author' => 'ProcessWire Modules Directory',
                'record_role' => 'Public author description',
                'gallery_title' => 'Public sources',
                'gallery_captions' => array('GitHub profile', 'Ichiban repository', 'ProcessWire author page'),
                'video_title' => 'ProcessWire history',
                'video_caption' => 'The official ProcessWire history video demonstrates the shared platform behind these community projects.',
                'theme' => 'glass', 'font' => 'inter', 'accent' => '#7c3aed', 'bg_type' => 'gradient', 'bg_value' => 'linear-gradient(135deg,#111827,#312e81,#7c3aed)',
                'alt' => array(
                    'lang' => 'ru',
                    'bio' => 'Full-stack разработчик в сфере электронной коммерции и автор модулей ProcessWire. В его публичном профиле автора Lynx представлен среди большой коллекции модулей для разработки, медиа, SEO и эксплуатации. Неофициальная витрина сообщества по публичным источникам.',
                    'project_title' => 'Избранный проект', 'project_body' => 'Комплексный SEO-модуль для ProcessWire CMS.', 'project_label' => 'Открыть репозиторий',
                    'record_title' => 'Публичная запись об авторе', 'record_text' => 'Full-stack разработчик электронной коммерции', 'record_role' => 'Описание в публичном профиле автора',
                    'gallery_title' => 'Публичные источники', 'gallery_captions' => array('Профиль GitHub', 'Репозиторий Ichiban', 'Страница автора ProcessWire'),
                    'video_title' => 'История ProcessWire', 'video_caption' => 'Официальное видео об истории ProcessWire показывает общую платформу, на которой создаются проекты сообщества.',
                    'profile_label' => 'Профиль автора', 'github_label' => 'GitHub', 'project_link_label' => 'Ichiban',
                ),
            ),
            array(
                'slug' => 'robin-sallis',
                'region' => 'New Zealand',
                'lang' => 'en',
                'title' => 'Robin Sallis',
                'bio' => 'ProcessWire module author known as Robin S and Toutouwai. The public module directory currently lists more modules under Robin S than under any other author. Unofficial community showcase based on public sources.',
                'avatar' => 'https://avatars.githubusercontent.com/u/1538852?v=4',
                'github_url' => 'https://github.com/Toutouwai',
                'author_url' => 'https://processwire.com/modules/author/robin-s/',
                'project_url' => 'https://github.com/Toutouwai/HannaCodeDialog',
                'project_name' => 'Hanna Code Dialog',
                'project_title' => 'Featured project',
                'project_body' => 'Enhancements for working with Hanna Code tags in CKEditor fields.',
                'project_label' => 'Open repository',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/Toutouwai/HannaCodeDialog',
                'record_title' => 'Official description',
                'record_text' => 'Provides a number of enhancements for working with Hanna Code tags in CKEditor.',
                'record_author' => 'Hanna Code Dialog',
                'record_role' => 'Official repository description',
                'gallery_title' => 'Public sources',
                'gallery_captions' => array('GitHub profile', 'Hanna Code Dialog repository', 'ProcessWire author page'),
                'video_title' => 'ProcessWire history',
                'video_caption' => 'The official history video introduces the open-source project supported by this module ecosystem.',
                'theme' => 'mono', 'font' => 'open-sans', 'accent' => '#111827', 'bg_type' => 'color', 'bg_value' => '#f4f4f5',
                'alt' => array(
                    'lang' => 'zh',
                    'bio' => 'ProcessWire 模块作者，社区昵称为 Robin S 和 Toutouwai。公开模块目录目前显示，Robin S 的模块数量多于其他作者。此为基于公开资料的非官方社区展示。',
                    'project_title' => '精选项目', 'project_body' => '增强在 CKEditor 字段中使用 Hanna Code 标签的体验。', 'project_label' => '打开代码仓库',
                    'record_title' => '官方说明', 'record_text' => '为在 CKEditor 中使用 Hanna Code 标签提供多项增强功能。', 'record_role' => '代码仓库官方说明',
                    'gallery_title' => '公开来源', 'gallery_captions' => array('GitHub 资料', 'Hanna Code Dialog 仓库', 'ProcessWire 作者页面'),
                    'video_title' => 'ProcessWire 历史', 'video_caption' => '官方历史视频介绍了由这个模块生态共同支持的开源项目。',
                    'profile_label' => '作者页面', 'github_label' => 'GitHub', 'project_link_label' => 'Hanna Code Dialog',
                ),
            ),
            array(
                'slug' => 'bernhard-baumrock',
                'region' => 'Vienna, Austria',
                'lang' => 'de',
                'title' => 'Bernhard Baumrock',
                'bio' => 'ProcessWire-Modulautor aus Wien. Sein öffentliches Autorenprofil umfasst die Rock-Modulfamilie für Frontend-Entwicklung, Migrationen, Deployment und Werkzeuge. Inoffizielle Community-Vitrine auf Basis öffentlicher Quellen.',
                'avatar' => 'https://avatars.githubusercontent.com/u/8488586?v=4',
                'github_url' => 'https://github.com/BernhardBaumrock',
                'author_url' => 'https://processwire.com/modules/author/bernhardbaumrock/',
                'project_url' => 'https://github.com/BernhardBaumrock/RockMigrations',
                'project_name' => 'RockMigrations',
                'project_title' => 'Ausgewähltes Projekt',
                'project_body' => 'Ein ProcessWire-Modul für Migrationen und Deployment zwischen Entwicklungs- und Live-Systemen.',
                'project_label' => 'Repository öffnen',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/BernhardBaumrock/RockMigrations',
                'record_title' => 'Offizielle Beschreibung',
                'record_text' => 'ProcessWire Module to handle Migrations from DEV<-->LIVE',
                'record_author' => 'RockMigrations',
                'record_role' => 'Offizielle Repository-Beschreibung',
                'gallery_title' => 'Öffentliche Quellen',
                'gallery_captions' => array('GitHub-Profil', 'RockMigrations-Repository', 'ProcessWire-Autorenseite'),
                'video_title' => 'ProcessWire-Geschichte',
                'video_caption' => 'Das offizielle Geschichtsvideo stellt die Open-Source-Plattform hinter dem Modul-Ökosystem vor.',
                'theme' => 'studio', 'font' => 'inter', 'accent' => '#ef4444', 'bg_type' => 'gradient', 'bg_value' => 'linear-gradient(135deg,#fff7ed,#fee2e2,#fef3c7)',
                'alt' => array(
                    'lang' => 'en',
                    'bio' => 'ProcessWire module author from Vienna. His public author profile includes the Rock family of modules for frontend development, migrations, deployment and tooling. Unofficial community showcase based on public sources.',
                    'project_title' => 'Featured project', 'project_body' => 'A ProcessWire module for migrations and deployment between development and live systems.', 'project_label' => 'Open repository',
                    'record_title' => 'Official description', 'record_text' => 'ProcessWire module for handling migrations from development to live systems.', 'record_role' => 'Official repository description',
                    'gallery_title' => 'Public sources', 'gallery_captions' => array('GitHub profile', 'RockMigrations repository', 'ProcessWire author page'),
                    'video_title' => 'ProcessWire history', 'video_caption' => 'The official history video introduces the open-source platform behind the module ecosystem.',
                    'profile_label' => 'Author page', 'github_label' => 'GitHub', 'project_link_label' => 'RockMigrations',
                ),
            ),
            array(
                'slug' => 'teppo-koivula',
                'region' => 'Ulvila, Finland',
                'lang' => 'fi',
                'title' => 'Teppo Koivula',
                'bio' => 'Suomalainen web-kehittäjä, ProcessWire Weekly -julkaisun tekijä ja pitkäaikainen ProcessWire-moduulien kirjoittaja. Epävirallinen yhteisöesittely, joka perustuu julkisiin lähteisiin.',
                'avatar' => 'https://avatars.githubusercontent.com/u/1252021?v=4',
                'github_url' => 'https://github.com/teppokoivula',
                'author_url' => 'https://processwire.com/modules/author/teppo/',
                'project_url' => 'https://github.com/teppokoivula/SearchEngine',
                'project_name' => 'SearchEngine',
                'project_title' => 'Esitelty projekti',
                'project_body' => 'ProcessWire CMS/CMF -moduuli sivuston sisällön indeksointiin ja hakemiseen.',
                'project_label' => 'Avaa tietovarasto',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/teppokoivula/SearchEngine',
                'record_title' => 'Virallinen kuvaus',
                'record_text' => 'SearchEngine is a ProcessWire CMS/CMF module for indexing and searching site contents.',
                'record_author' => 'SearchEngine',
                'record_role' => 'Virallinen tietovaraston kuvaus',
                'gallery_title' => 'Julkiset lähteet',
                'gallery_captions' => array('GitHub-profiili', 'SearchEngine-tietovarasto', 'ProcessWire-tekijäsivu'),
                'video_title' => 'ProcessWiren historia',
                'video_caption' => 'Virallinen historiavideo esittelee avoimen lähdekoodin projektin moduuliekosysteemin taustalla.',
                'theme' => 'pill', 'font' => 'noto-sans', 'accent' => '#0f766e', 'bg_type' => 'color', 'bg_value' => '#ecfdf5',
                'alt' => array(
                    'lang' => 'en',
                    'bio' => 'Web developer from Finland, author of ProcessWire Weekly and a long-time ProcessWire module author. Unofficial community showcase based on public sources.',
                    'project_title' => 'Featured project', 'project_body' => 'A ProcessWire CMS/CMF module for indexing and searching site contents.', 'project_label' => 'Open repository',
                    'record_title' => 'Official description', 'record_text' => 'SearchEngine is a ProcessWire CMS/CMF module for indexing and searching site contents.', 'record_role' => 'Official repository description',
                    'gallery_title' => 'Public sources', 'gallery_captions' => array('GitHub profile', 'SearchEngine repository', 'ProcessWire author page'),
                    'video_title' => 'ProcessWire history', 'video_caption' => 'The official history video introduces the open-source project behind the module ecosystem.',
                    'profile_label' => 'Author page', 'github_label' => 'GitHub', 'project_link_label' => 'SearchEngine',
                ),
            ),
            array(
                'slug' => 'adrian-jones',
                'region' => 'British Columbia, Canada',
                'lang' => 'en',
                'title' => 'Adrian Jones',
                'bio' => 'ProcessWire module author and core contributor based in British Columbia, Canada. He is best known in the module directory for Tracy Debugger and a broad set of administration tools. Unofficial community showcase based on public sources.',
                'avatar' => 'https://avatars.githubusercontent.com/u/871211?v=4',
                'github_url' => 'https://github.com/adrianbj',
                'author_url' => 'https://processwire.com/modules/author/adrian-jones/',
                'project_url' => 'https://github.com/adrianbj/TracyDebugger',
                'project_name' => 'Tracy Debugger',
                'project_title' => 'Featured project',
                'project_body' => 'A debugging and development tool for ProcessWire.',
                'project_label' => 'Open repository',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/adrianbj/TracyDebugger',
                'record_title' => 'Official description',
                'record_text' => 'The ultimate debugging and development tool for ProcessWire',
                'record_author' => 'Tracy Debugger',
                'record_role' => 'Official repository description',
                'gallery_title' => 'Public sources',
                'gallery_captions' => array('GitHub profile', 'Tracy Debugger repository', 'ProcessWire author page'),
                'video_title' => 'ProcessWire history',
                'video_caption' => 'The official history video introduces the platform supported by ProcessWire development tools.',
                'theme' => 'glass', 'font' => 'open-sans', 'accent' => '#2563eb', 'bg_type' => 'gradient', 'bg_value' => 'linear-gradient(135deg,#0f172a,#1d4ed8,#06b6d4)',
                'alt' => array(
                    'lang' => 'fr',
                    'bio' => 'Auteur de modules ProcessWire et contributeur au cœur du projet, basé en Colombie-Britannique au Canada. Il est surtout connu dans le catalogue pour Tracy Debugger et de nombreux outils d’administration. Vitrine communautaire non officielle fondée sur des sources publiques.',
                    'project_title' => 'Projet présenté', 'project_body' => 'Un outil de débogage et de développement pour ProcessWire.', 'project_label' => 'Ouvrir le dépôt',
                    'record_title' => 'Description officielle', 'record_text' => 'L’outil ultime de débogage et de développement pour ProcessWire.', 'record_role' => 'Description officielle du dépôt',
                    'gallery_title' => 'Sources publiques', 'gallery_captions' => array('Profil GitHub', 'Dépôt Tracy Debugger', 'Page auteur ProcessWire'),
                    'video_title' => 'Histoire de ProcessWire', 'video_caption' => 'La vidéo historique officielle présente la plateforme accompagnée par les outils de développement ProcessWire.',
                    'profile_label' => 'Page auteur', 'github_label' => 'GitHub', 'project_link_label' => 'Tracy Debugger',
                ),
            ),
            array(
                'slug' => 'peter-knight',
                'region' => 'Dublin, Ireland',
                'lang' => 'en',
                'title' => 'Peter Knight',
                'bio' => 'ProcessWire community member and module author based in Dublin, Ireland. His public work includes SeoNeo, MediaHub and PromptWire MCP. Unofficial community showcase based on public sources.',
                'avatar' => 'https://avatars.githubusercontent.com/u/1786476?v=4',
                'github_url' => 'https://github.com/PeterKnightDigital',
                'author_url' => 'https://processwire.com/modules/author/peter-knight/',
                'project_url' => 'https://github.com/PeterKnightDigital/SeoNeo',
                'project_name' => 'SeoNeo',
                'project_title' => 'Featured project',
                'project_body' => 'A modern SEO coordinator for ProcessWire that uses native fields for metadata, robots directives, canonical URLs and more.',
                'project_label' => 'Open repository',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/PeterKnightDigital/SeoNeo',
                'record_title' => 'Official description',
                'record_text' => 'Modern SEO coordinator for ProcessWire — uses native PW fields for meta, robots, canonical, and more.',
                'record_author' => 'SeoNeo',
                'record_role' => 'Official repository description',
                'gallery_title' => 'Public sources',
                'gallery_captions' => array('GitHub profile', 'SeoNeo repository', 'ProcessWire author page'),
                'video_title' => 'ProcessWire history',
                'video_caption' => 'The official history video introduces the open-source platform behind the community module ecosystem.',
                'theme' => 'mono', 'font' => 'roboto', 'accent' => '#b45309', 'bg_type' => 'color', 'bg_value' => '#fffbeb',
                'alt' => array(
                    'lang' => 'de',
                    'bio' => 'ProcessWire-Community-Mitglied und Modulautor aus Dublin, Irland. Zu seinen öffentlichen Projekten gehören SeoNeo, MediaHub und PromptWire MCP. Inoffizielle Community-Vitrine auf Basis öffentlicher Quellen.',
                    'project_title' => 'Ausgewähltes Projekt', 'project_body' => 'Ein moderner SEO-Koordinator für ProcessWire, der native Felder für Metadaten, Robots-Anweisungen, kanonische URLs und mehr verwendet.', 'project_label' => 'Repository öffnen',
                    'record_title' => 'Offizielle Beschreibung', 'record_text' => 'Moderner SEO-Koordinator für ProcessWire mit nativen Feldern für Meta-Daten, Robots, Canonical und mehr.', 'record_role' => 'Offizielle Repository-Beschreibung',
                    'gallery_title' => 'Öffentliche Quellen', 'gallery_captions' => array('GitHub-Profil', 'SeoNeo-Repository', 'ProcessWire-Autorenseite'),
                    'video_title' => 'ProcessWire-Geschichte', 'video_caption' => 'Das offizielle Geschichtsvideo stellt die Open-Source-Plattform hinter dem Modul-Ökosystem der Community vor.',
                    'profile_label' => 'Autorenseite', 'github_label' => 'GitHub', 'project_link_label' => 'SeoNeo',
                ),
            ),
            array(
                'slug' => 'wbmnfktr',
                'region' => 'Germany',
                'lang' => 'en',
                'title' => 'Alexander Abelt (wbmnfktr)',
                'bio' => 'Alexander Abelt is a German online marketing, SEO and web development specialist and a long-time ProcessWire community contributor known as wbmnfktr. His current work focuses on search-optimized websites, marketing strategy and custom automation. Unofficial community showcase based on public sources.',
                'avatar' => 'https://avatars.githubusercontent.com/u/10993474?v=4',
                'github_url' => 'https://github.com/acabelt',
                'author_url' => 'https://alexanderabelt.com/',
                'profile_label' => 'Personal website',
                'project_url' => 'https://processwire.recipes/',
                'project_name' => 'ProcessWire Recipes',
                'project_title' => 'Featured project',
                'project_body' => 'A community collection of ProcessWire API snippets, complete solutions and practical helpers.',
                'project_label' => 'Open project',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/processwire/processwire',
                'record_title' => 'Public project description',
                'record_text' => 'A collection of ProcessWire API snippets to solve common tasks, provide full solutions, and some little helpers that make work with the API easier.',
                'record_author' => 'ProcessWire Recipes',
                'record_role' => 'Public project description',
                'gallery_title' => 'Public sources',
                'gallery_captions' => array('GitHub profile', 'ProcessWire Recipes', 'Personal website'),
                'video_title' => 'ProcessWire history',
                'video_caption' => 'The official history video introduces the open-source platform shared by ProcessWire community contributors.',
                'theme' => 'studio', 'font' => 'noto-serif', 'accent' => '#9333ea', 'bg_type' => 'gradient', 'bg_value' => 'linear-gradient(135deg,#faf5ff,#f3e8ff,#e0e7ff)',
                'alt' => array(
                    'lang' => 'de',
                    'bio' => 'Alexander Abelt ist ein deutscher Spezialist für Online-Marketing, SEO und Webentwicklung sowie ein langjähriger ProcessWire-Community-Mitwirkender, bekannt als wbmnfktr. Seine aktuelle Arbeit konzentriert sich auf suchmaschinenoptimierte Websites, Marketingstrategien und individuelle Automatisierung. Inoffizielle Community-Vitrine auf Basis öffentlicher Quellen.',
                    'project_title' => 'Ausgewähltes Projekt', 'project_body' => 'Eine Community-Sammlung mit ProcessWire-API-Snippets, vollständigen Lösungen und praktischen Helfern.', 'project_label' => 'Projekt öffnen',
                    'record_title' => 'Öffentliche Projektbeschreibung', 'record_text' => 'Eine Sammlung von ProcessWire-API-Snippets für häufige Aufgaben, vollständige Lösungen und kleine Helfer für die Arbeit mit der API.', 'record_role' => 'Öffentliche Projektbeschreibung',
                    'gallery_title' => 'Öffentliche Quellen', 'gallery_captions' => array('GitHub-Profil', 'ProcessWire Recipes', 'Persönliche Website'),
                    'video_title' => 'ProcessWire-Geschichte', 'video_caption' => 'Das offizielle Geschichtsvideo stellt die Open-Source-Plattform der ProcessWire-Community vor.',
                    'profile_label' => 'Persönliche Website', 'github_label' => 'GitHub', 'project_link_label' => 'ProcessWire Recipes',
                ),
            ),
            array(
                'slug' => 'jonathan-lahijani',
                'region' => 'Los Angeles, California, USA',
                'lang' => 'en',
                'title' => 'Jonathan Lahijani',
                'bio' => 'Long-time ProcessWire community member, module author and video educator based in Los Angeles. His public work includes InputfieldPageModalSelect and the WordPress vs. ProcessWire video series. Unofficial community showcase based on public sources.',
                'avatar' => 'https://avatars.githubusercontent.com/u/4558?v=4',
                'github_url' => 'https://github.com/jlahijani',
                'author_url' => 'https://processwire.com/modules/author/jonathan-lahijani/',
                'project_url' => 'https://processwire.com/modules/inputfield-page-modal-select/',
                'project_name' => 'InputfieldPageModalSelect',
                'project_title' => 'Featured project',
                'project_body' => 'A ProcessWire inputfield for selecting pages from a searchable modal with checkboxes.',
                'project_label' => 'Open module page',
                'project_image' => 'https://opengraph.githubassets.com/lynx-demo/jlahijani/InputfieldPageModalSelect',
                'record_title' => 'Module directory description',
                'record_text' => 'Select multiple pages from a searchable modal with checkboxes.',
                'record_author' => 'InputfieldPageModalSelect',
                'record_role' => 'ProcessWire module directory description',
                'gallery_title' => 'Public sources',
                'gallery_captions' => array('GitHub profile', 'Module project', 'ProcessWire author page'),
                'video_title' => 'ProcessWire history',
                'video_caption' => 'The official history video introduces the platform featured throughout ProcessWire community education.',
                'theme' => 'pill', 'font' => 'noto-sans', 'accent' => '#2563eb', 'bg_type' => 'color', 'bg_value' => '#eff6ff',
                'alt' => array(
                    'lang' => 'es',
                    'bio' => 'Miembro veterano de la comunidad ProcessWire, autor de módulos y educador en vídeo con sede en Los Ángeles. Su trabajo público incluye InputfieldPageModalSelect y la serie de vídeos WordPress vs. ProcessWire. Muestra comunitaria no oficial basada en fuentes públicas.',
                    'project_title' => 'Proyecto destacado', 'project_body' => 'Un campo de entrada de ProcessWire para seleccionar páginas desde una ventana modal con búsqueda y casillas.', 'project_label' => 'Abrir página del módulo',
                    'record_title' => 'Descripción del directorio', 'record_text' => 'Selecciona varias páginas desde una ventana modal con búsqueda y casillas.', 'record_role' => 'Descripción del directorio de módulos de ProcessWire',
                    'gallery_title' => 'Fuentes públicas', 'gallery_captions' => array('Perfil de GitHub', 'Proyecto del módulo', 'Página de autor de ProcessWire'),
                    'video_title' => 'Historia de ProcessWire', 'video_caption' => 'El vídeo oficial de historia presenta la plataforma explicada en los recursos educativos de la comunidad ProcessWire.',
                    'profile_label' => 'Página de autor', 'github_label' => 'GitHub', 'project_link_label' => 'InputfieldPageModalSelect',
                ),
            ),
            array(
                'slug' => 'jploch',
                'region' => 'Hamburg, Germany',
                'lang' => 'de',
                'title' => 'Jan Ploch (jploch)',
                'bio' => 'Jan Ploch ist Grafikdesigner und Webentwickler aus Hamburg. Sein 2015 gegründetes Büro arbeitet medienübergreifend an Markenidentitäten, Websites, Büchern, Schriften und Illustrationen. Er entwickelte PAGEGRID und arbeitet mit Diogo Oliveira im KONKAT Studio, das am neuen ProcessWire-Webdesign und der AdminThemeUikit-Variante Konkat Default mitwirkte. Inoffizielle Community-Vitrine auf Basis öffentlicher Quellen.',
                'avatar' => 'https://avatars.githubusercontent.com/u/45133688?v=4',
                'github_url' => 'https://github.com/jploch',
                'author_url' => 'https://www.janploch.de/',
                'profile_label' => 'Persönliches Portfolio',
                'project_url' => 'https://github.com/jploch/FieldtypePageGrid',
                'project_name' => 'PAGEGRID',
                'project_title' => 'Ausgewähltes Projekt',
                'project_body' => 'Ein visueller Seitenersteller mit einem intuitiven Editor und vollständiger ProcessWire-Integration.',
                'project_label' => 'Repository öffnen',
                'project_image' => 'https://page-grid.com/site/templates/img/pg_logo_icon.png',
                'record_title' => 'Verzeichnisbeschreibung',
                'record_text' => 'Visuelles Erstellen mit dem intuitiven PAGEGRID-Editor, nahtlos integriert in ProcessWires API, Felder und Berechtigungen.',
                'record_author' => 'PAGEGRID',
                'record_role' => 'Beschreibung im ProcessWire-Modulverzeichnis',
                'gallery_title' => 'Öffentliche Quellen',
                'gallery_captions' => array('GitHub-Profil', 'PAGEGRID-Repository', 'Persönliches Portfolio'),
                'video_title' => 'ProcessWire-Geschichte',
                'video_caption' => 'Das offizielle Geschichtsvideo stellt die Open-Source-Plattform hinter PAGEGRID vor.',
                'theme' => 'default', 'font' => 'roboto', 'accent' => '#dc2626', 'bg_type' => 'color', 'bg_value' => '#fff7ed',
                'alt' => array(
                    'lang' => 'en',
                    'bio' => 'Jan Ploch is a graphic designer and web developer from Hamburg, Germany. Founded in 2015, his studio works across brand identities, websites, books, typefaces and illustration. He created PAGEGRID and works with Diogo Oliveira at KONKAT Studio, which contributed the new ProcessWire website design and the Konkat Default AdminThemeUikit option. Unofficial community showcase based on public sources.',
                    'project_title' => 'Featured project', 'project_body' => 'A visual page builder with an intuitive editor and full ProcessWire integration.', 'project_label' => 'Open repository',
                    'record_title' => 'Directory description', 'record_text' => 'Build visually with PAGEGRID’s intuitive editor, seamlessly integrated with ProcessWire’s API, fields, and permissions for full power and flexibility.', 'record_role' => 'ProcessWire module directory description',
                    'gallery_title' => 'Public sources', 'gallery_captions' => array('GitHub profile', 'PAGEGRID repository', 'Personal portfolio'),
                    'video_title' => 'ProcessWire history', 'video_caption' => 'The official history video introduces the open-source platform behind PAGEGRID.',
                    'profile_label' => 'Personal portfolio', 'github_label' => 'GitHub', 'project_link_label' => 'PAGEGRID',
                ),
            ),
        );

        foreach($profiles as &$p) {
            $lang = $p['alt']['lang'];
            $p['demo_region'] = $p['region'];
            unset($p['region']);
            $p['seo_title'] = $p['title'] . ' — ProcessWire community showcase';
            $p['seo_description'] = $p['bio'];
            $p['og_image'] = $p['avatar'];
            $p['noindex'] = 0;
            $p['custom_css'] = '';
            $p['active'] = 1;
            $p['translations'] = array($lang => array(
                'title' => $p['title'],
                'bio' => $p['alt']['bio'],
                'seo_title' => $p['title'] . ' — ProcessWire community showcase',
                'seo_description' => $p['alt']['bio'],
            ));
            $p['links'] = array(
                $link($p['profile_label'] ?? 'ProcessWire profile', $p['author_url'], 'user', 0, 0, $lang, $p['alt']['profile_label']),
                $link('GitHub', $p['github_url'], 'github', 1, 1, $lang, $p['alt']['github_label']),
                $link($p['project_name'], $p['project_url'], 'code', 2, 0, $lang, $p['alt']['project_link_label']),
            );
            $p['blocks'] = array($project($p), $quote($p), $gallery($p), $video($p));
            foreach(array(
                'github_url', 'author_url', 'project_url', 'project_name', 'project_title',
                'project_body', 'project_label', 'project_image', 'record_title', 'record_text',
                'record_author', 'record_role', 'gallery_title', 'gallery_captions',
                'video_title', 'video_caption', 'profile_label', 'alt'
            ) as $key) unset($p[$key]);
        }
        unset($p);

        return array(
            'lynx_export' => 1,
            'version' => self::getModuleInfo()['version'],
            'profiles' => $profiles,
        );
    }
}
